import { ChakraProvider } from "@chakra-ui/react";
import dayjs from "dayjs";
import Duration from "dayjs/plugin/duration";
import LocalizedFormat from "dayjs/plugin/localizedFormat";
import RelativeTime from "dayjs/plugin/relativeTime";
import Timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import "locales/i18n";
import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClientProvider } from "react-query";
import { queryClient } from "utils/react-query";
import { applyDashboardTheme, DashboardThemeProvider, getStoredTheme } from "contexts/ThemeContext";
import { theme } from "../chakra.config";
import App from "./App";
import "index.scss";
import "theme/palettes.scss";
dayjs.extend(Timezone);dayjs.extend(LocalizedFormat);dayjs.extend(utc);dayjs.extend(RelativeTime);dayjs.extend(Duration);
window.localStorage.setItem("chakra-ui-color-mode","dark");applyDashboardTheme(getStoredTheme());
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(<React.StrictMode><DashboardThemeProvider><ChakraProvider theme={theme}><QueryClientProvider client={queryClient}><App /></QueryClientProvider></ChakraProvider></DashboardThemeProvider></React.StrictMode>);
