# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/xmc/config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'transport/internet/finalmask/xmc/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-transport/internet/finalmask/xmc/config.proto\x12%xray.transport.internet.finalmask.xmc\"p\n\x06\x43onfig\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x11\n\tusernames\x18\x02 \x03(\t\x12\x17\n\x0frsa_private_key\x18\x08 \x01(\x0c\x12\x16\n\x0ersa_public_key\x18\t \x01(\x0c\x12\x10\n\x08hostname\x18\n \x01(\tB\x91\x01\n)com.xray.transport.internet.finalmask.xmcP\x01Z:github.com/xtls/xray-core/transport/internet/finalmask/xmc\xaa\x02%Xray.Transport.Internet.Finalmask.XMCb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.xmc.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.xray.transport.internet.finalmask.xmcP\001Z:github.com/xtls/xray-core/transport/internet/finalmask/xmc\252\002%Xray.Transport.Internet.Finalmask.XMC'
  _globals['_CONFIG']._serialized_start=88
  _globals['_CONFIG']._serialized_end=200
# @@protoc_insertion_point(module_scope)
