# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/xicmp/config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'transport/internet/finalmask/xicmp/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/transport/internet/finalmask/xicmp/config.proto\x12\'xray.transport.internet.finalmask.xicmp\"$\n\x06\x43onfig\x12\r\n\x05\x44GRAM\x18\x01 \x01(\x08\x12\x0b\n\x03IPs\x18\x02 \x03(\tB\x97\x01\n+com.xray.transport.internet.finalmask.xicmpP\x01Z<github.com/xtls/xray-core/transport/internet/finalmask/xicmp\xaa\x02\'Xray.Transport.Internet.Finalmask.Xicmpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.xicmp.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.xray.transport.internet.finalmask.xicmpP\001Z<github.com/xtls/xray-core/transport/internet/finalmask/xicmp\252\002\'Xray.Transport.Internet.Finalmask.Xicmp'
  _globals['_CONFIG']._serialized_start=92
  _globals['_CONFIG']._serialized_end=128
# @@protoc_insertion_point(module_scope)
