# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/realm/config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'transport/internet/finalmask/realm/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xray_api.proto.transport.internet.tls import config_pb2 as transport_dot_internet_dot_tls_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/transport/internet/finalmask/realm/config.proto\x12\'xray.transport.internet.finalmask.realm\x1a#transport/internet/tls/config.proto\"\x9e\x01\n\x06\x43onfig\x12\x0e\n\x06scheme\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\x12\n\n\x02ID\x18\x05 \x01(\t\x12\x14\n\x0cstun_servers\x18\x06 \x03(\t\x12\x37\n\ntls_config\x18\x07 \x01(\x0b\x32#.xray.transport.internet.tls.ConfigB\x97\x01\n+com.xray.transport.internet.finalmask.realmP\x01Z<github.com/xtls/xray-core/transport/internet/finalmask/realm\xaa\x02\'Xray.Transport.Internet.Finalmask.Realmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.realm.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.xray.transport.internet.finalmask.realmP\001Z<github.com/xtls/xray-core/transport/internet/finalmask/realm\252\002\'Xray.Transport.Internet.Finalmask.Realm'
  _globals['_CONFIG']._serialized_start=130
  _globals['_CONFIG']._serialized_end=288
# @@protoc_insertion_point(module_scope)
