# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/finalmask/mkcp/header/config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'transport/internet/finalmask/mkcp/header/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5transport/internet/finalmask/mkcp/header/config.proto\x12-xray.transport.internet.finalmask.mkcp.header\"$\n\x06\x43onfig\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tB\xa9\x01\n1com.xray.transport.internet.finalmask.mkcp.headerP\x01ZBgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/header\xaa\x02-Xray.Transport.Internet.Finalmask.Mkcp.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transport.internet.finalmask.mkcp.header.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.xray.transport.internet.finalmask.mkcp.headerP\001ZBgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/header\252\002-Xray.Transport.Internet.Finalmask.Mkcp.Header'
  _globals['_CONFIG']._serialized_start=104
  _globals['_CONFIG']._serialized_end=140
# @@protoc_insertion_point(module_scope)
